services:
  # --- 1. GATEWAY & SSL ---
  nginx:
    image: nginx:alpine
    container_name: energy_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - energy_network

  certbot:
    image: certbot/certbot
    container_name: energy_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Tự động check gia hạn chứng chỉ mỗi 12h
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - energy_network

  # --- 2. DATABASE ---
  postgres:
    image: postgres:15-alpine
    container_name: energy_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Dùng cho DBeaver
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backend/docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - energy_network

  mongo:
    image: mongo:6.0
    container_name: energy_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - energy_network

  # --- 3. APP SERVICES ---
  backend:
    build:
      context: ./backend
      dockerfile: docker/backend/Dockerfile
    container_name: energy_backend
    restart: always
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
    # Chạy ở port 8000 nội bộ
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/static:/app/static
    networks:
      - energy_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: energy_frontend
    restart: always
    depends_on:
      - backend
    environment:
      # URL này Client sẽ gọi, nên phải là https://zenergy.cloud/api
      NEXT_PUBLIC_API_URL: https://zenergy.cloud/api
    extra_hosts:
      - "zenergy.cloud:host-gateway"
    expose:
      - "3000"
    networks:
      - energy_network

networks:
  energy_network:
    driver: bridge

volumes:
  pg_data:
  mongo_data: